### ISSUE TITLE
Hugo module failure

### ISSUE THREAD

**Issue by mutageneral** [LordMathis/hugo-theme-nightfall#10]
I tried to use it as a Hugo module and it did not work:

```
go: no module dependencies to download
go: github.com/LordMathis/hugo-theme-nightfall: invalid github.com import path "github.com/LordMathis"
Error: failed to get ["-d" "-u" "github.com/LordMathis/hugo-theme-nightfall"]: failed to execute 'go [get -d -u github.com/LordMathis/hugo-theme-nightfall]': failed to execute binary "go" with args [get -d -u github.com/LordMathis/hugo-theme-nightfall]: go: github.com/LordMathis/hugo-theme-nightfall: invalid github.com import path "github.com/LordMathis"
 *errors.errorString
```

this is my go.mod:

```
module github.com/LordMathis/hugo-theme-nightfall

go 1.20
```

this is what I have in my config.toml

```toml
[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'
```

I followed [the documentation](https://gohugo.io/hugo-modules/use-modules/#use-a-module-for-a-theme) and the instructions in the README.

So I switched to using a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for now. I don't know what I'm doing with eider, but at least this one works.

**Comment by LordMathis** [comment]
Your go.mod is wrong. The module should be name of your blog, You probably run `hugo mod init` with the module of the theme instead of your own module. Try deleting `go.mod` and `go.sum` and rerun `hugo mod init blog`. Also take a look at how other people use the theme as module here:  https://github.com/LordMathis/hugo-theme-nightfall/network/dependents
